# Generated by Django 4.2 on 2023-04-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TradeApp', '0002_mymodelname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
