# Generated by Django 4.2 on 2023-04-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TradeApp', '0003_delete_mymodelname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='UserInfo',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='first_name',
            new_name='api',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='last_name',
            new_name='secret',
        ),
    ]
