# Generated by Django 4.2 on 2023-05-01 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradeApp', '0004_rename_person_userinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='api',
            field=models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
