# Generated by Django 4.2 on 2023-05-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TradeApp', '0005_alter_userinfo_api'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
